export const GET_BOOK_BORROW_BY_STUDENTID = 'GET_BOOK_BORROW_BY_STUDENTID'

export const DELETE_BOOK_BY_ID = 'DELETE_BOOK_BY_ID'

export const RECREATE_BOOK_BY_ID = 'RECREATE_BOOK_BY_ID'

export const  UPDATE_BOOK_BY_ID = 'UPDDATE_BOOK_BY_ID'

export const SUBMIT_UPDATE_BOOK = 'SUBMIT_UPDATE_BOOK'

export const BORROW_BOOK_BY_USERID = 'BORROW_BOOK_BY_USERID'