export const GET_USERID_CLICK = 'GET_USERID_CLICK'

export const CHARGE_CARD_USERID = 'CHARGE_CARD_USERID'

export const SUBMIT_CHARGE = 'SUBMIT_CHARGE'

export const BALANCE_OF_USERID = 'BALANCE_OF_USERID'
