export const LOGIN = 'LOGIN'

export const GET_STUDENT_BY_ADMIN = 'GET_STUDENT_BY_ADMIN'

export const DELETE_STUDENT_SAGA = 'DELETE_STUDENT_SAGA'

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

export const VALUE_REGISTER_ADMIN = 'VALUE_REGISTER_ADMIN'

export const STATUS_REGISTER_ADMIN = 'STATUS_REGISTER_ADMIN'